#!/usr/bin/env bash

set -euf -o pipefail

function install() {
  brew install $1
}

brew tap homebrew/cask-versions

install 1password
install sync
install google-chrome
install firefox-developer-edition
install vscodium
install colima
install fnm
install git
install z
install flycut
install iterm2
install quicksilver
install istat-menus
install gpg-suite
install spotify
install vlc
install slack
install discord
install zoom
install unar