#!/usr/bin/env bash

set -euf -o pipefail

function install() {
  brew install $1
}

brew tap homebrew/cask-versions

install google-chrome
install dropbox
install flycut
install 1password6
install iterm2
install vscodium
install gpg-suite
install quicksilver
install docker
install sync
install zoom
install spotify
install vlc
install git
install slack
install discord